### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by jlebar** [bgirard/hacky.mk#5]
After resolving #4:

```
$ python ../src/tools/hackymake/hackypost.py 
Traceback (most recent call last):
  File "../src/tools/hackymake/hackypost.py", line 818, in <module>
    tree_base = os.path.abspath(args.pop(0))
IndexError: pop from empty list
```

**Comment by jlebar** [comment]
Oh,  do you want me to pass a directory to this thing?  I ran it with --help and then again with "."; I'm not sure if I messed something up.  :)

**Comment by vvuk** [comment]
Erm, yes, pass a dir (your objdir, ideally ".").  My bad, it should
probably default there :)

**Comment by djg** [comment]
``` sh
python tools/hackymake/hackypost.py ./objdir-droid
```

fails with

```
Traceback (most recent call last):
  File "tools/hackymake/hackpost.py", line 829, in <module>
    buildNinjaBuild()
  File "tools/hackymake/hackypost.py", line 804, in buildNinjaBuild
    for fn in os.listdir(os.path.join(".hacky", "ninja")):
OSError: [Errno 2] No such file or directory: '.hacky/ninja'
```

but 

``` sh
cd objdir-droid && python ../tools/hackymake/hackypost.py .
```

succeeds.
